# Generated by Django 5.2.6 on 2026-04-27 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='subscriptio_status_fc7385_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['user', '-created_at'], name='token_trans_user_id_b43318_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['subscription', '-created_at'], name='token_trans_subscri_db7f72_idx'),
        ),
    ]
