# Generated by Django 5.2.6 on 2026-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD')], default='EGP', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('go', 'GO'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
