# Generated by Django 5.2.6 on 2026-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the login attempt was made')),
                ('username', models.CharField(help_text='Username used in the login attempt', max_length=150)),
                ('success', models.BooleanField(default=False, help_text='Whether the login attempt was successful')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user_Agent', models.TextField(blank=True, help_text='User agent string of the client')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for login failure, if applicable', max_length=100)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='TOTP secret key', max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Wheter 2FA is currently active')),
                ('backup_codes', models.JSONField(default=list, help_text='List of backup codes for accout recovery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Two Factor Authentication',
                'verbose_name_plural': 'Two Factor Authentications',
                'db_table': 'two_factor_auth',
            },
        ),
    ]
