# Generated by Django 5.2.6 on 2026-04-29 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_pending_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='organization',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'organization'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
