# Generated by Django 5.2.6 on 2026-05-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_org_to_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='registration_type',
            field=models.CharField(choices=[('basic', 'Basic User'), ('organization', 'Organization Admin'), ('org_user', 'Organization User')], max_length=20),
        ),
    ]
