services:
  # =========================
  # Django Backend (Daphne)
  # =========================
  backend:
    container_name: tafahom-backend
    build:
      context: .
    env_file:
      - .env.prod
    environment:
      DJANGO_SETTINGS_MODULE: tafahom_api.settings
      ENVIRONMENT: PROD
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD
    command: >
      sh -c "python manage.py migrate && python manage.py setup_plans && python manage.py award_weekly_tokens && python manage.py createsuperuser --noinput || true && daphne -b 0.0.0.0 -p 8000 tafahom_api.asgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  # =========================
  # PostgreSQL
  # =========================
  postgres:
    image: postgres:17-alpine
    container_name: tafahom-postgres
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # =========================
  # Redis
  # =========================
  redis:
    image: redis:7-alpine
    container_name: tafahom-redis
    restart: unless-stopped

  # =========================
  # pgAdmin (FIXED)
  # =========================
  pgadmin:
    image: dpage/pgadmin4
    container_name: tafahom-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tafahom.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_APPLICATION_ROOT: "\"/pgadmin\""
      GUNICORN_TIMEOUT: "400"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  # =========================
  # Coturn (WebRTC TURN Server)
  # =========================
  coturn:
    image: coturn/coturn
    container_name: tafahom-turn
    network_mode: "host"
    restart: unless-stopped
    command: >
      -n --log-file=stdout --min-port=49152 --max-port=65535 --realm=tafahom.com --user=tafahom_admin:StrongPassword123 --lt-cred-mech --external-ip=72.62.145.111

# =========================
# Volumes
# =========================
volumes:
  postgres_data:
  static_volume:
  media_volume:
