# =========================
# Network
# =========================
listening-port=3478
tls-listening-port=5349

listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=72.62.145.111

# =========================
# Authentication
# =========================
lt-cred-mech
user=tafahom_admin:StrongPassword123
realm=tafahom.com

# =========================
# Ports (FIXED)
# =========================
min-port=10000
max-port=10100

# =========================
# Security
# =========================
no-cli
no-loopback-peers
no-multicast-peers

# =========================
# Disable TLS (temporary)
# =========================
no-tls
no-dtls

# =========================
# Logging
# =========================
log-file=stdout
verbos