# Generated by Django 5.2.6 on 2026-01-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('context', models.CharField(blank=True, max_length=100)),
                ('text_en', models.TextField(verbose_name='English Text')),
                ('text_ar', models.TextField(verbose_name='Arabic Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Translation Key',
                'verbose_name_plural': 'Translation Keys',
                'db_table': 'translation_keys',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='translation_key_925a2d_idx'), models.Index(fields=['context'], name='translation_context_d4dc5b_idx')],
            },
        ),
    ]
