# Generated by Django 5.2.6 on 2026-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignLanguageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ase', 'American Sign Language'), ('egs', 'Egyptian Sign Language')], max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('supported_spoken_languages', models.JSONField(default=list)),
                ('has_avatar_support', models.BooleanField(default=False)),
                ('has_video_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Sign Language Configuration',
                'verbose_name_plural': 'Sign Language Configurations',
                'db_table': 'sign_language_configs',
            },
        ),
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_sign', 'To Sign Language'), ('from_sign', 'From Sign Language')], max_length=20)),
                ('processing_mode', models.CharField(choices=[('standard', 'Standard'), ('realtime', 'Realtime')], default='standard', max_length=20)),
                ('source_language', models.CharField(choices=[('en-US', 'English (US)'), ('ar-EG', 'Arabic (Egypt)')], default='ar-EG', max_length=10)),
                ('target_sign_language', models.CharField(blank=True, choices=[('ase', 'American Sign Language'), ('egs', 'Egyptian Sign Language')], max_length=10, null=True)),
                ('output_spoken_language', models.CharField(blank=True, choices=[('en-US', 'English (US)'), ('ar-EG', 'Arabic (Egypt)')], max_length=10, null=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('video', 'Video')], max_length=10)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('input_audio', models.FileField(blank=True, null=True, upload_to='translation/input/audio/%Y/%m/%d/')),
                ('input_video', models.FileField(blank=True, null=True, upload_to='translation/input/video/%Y/%m/%d/')),
                ('output_type', models.CharField(choices=[('avatar', '3D Avatar'), ('video', 'Video'), ('text', 'Text'), ('voice', 'Voice')], max_length=10)),
                ('output_text', models.TextField(blank=True, null=True)),
                ('output_audio', models.FileField(blank=True, null=True, upload_to='translation/output/audio/%Y/%m/%d/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='translation/output/video/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'translation_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
