# Generated by Django 5.2.6 on 2026-01-09 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='translationrequest',
            index=models.Index(fields=['user', '-created_at'], name='translation_user_id_f6aa35_idx'),
        ),
        migrations.AddIndex(
            model_name='translationrequest',
            index=models.Index(fields=['status'], name='translation_status_11cfc1_idx'),
        ),
        migrations.AddIndex(
            model_name='translationrequest',
            index=models.Index(fields=['direction'], name='translation_directi_aa0120_idx'),
        ),
        migrations.AddIndex(
            model_name='translationrequest',
            index=models.Index(fields=['target_sign_language'], name='translation_target__93e084_idx'),
        ),
    ]
