# Generated by Django 5.2.6 on 2026-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
