# Generated by Django 5.2.6 on 2026-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('basic_user', 'Basic User'), ('organization', 'Organization'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='basic_user', max_length=20),
        ),
    ]
