# Generated by Django 5.2.6 on 2026-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_organization_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
