import os
import subprocess
import logging
from youtube_transcript_api import YouTubeTranscriptApi
from tafahom_api.apps.v1.translation.services.youtube_service import download_youtube_audio
from tafahom_api.apps.v1.ai.clients.speech_to_text_client import SpeechToTextClient
import httpx
from asgiref.sync import async_to_sync

logger = logging.getLogger(__name__)

def extract_transcript(youtube_url):
    """
    Step 1: Attempt youtube-transcript-api (arabic manual, then autogenerated)
    Step 2: Fallback to yt-dlp + ffmpeg + Whisper
    """
    video_id = _extract_video_id(youtube_url)
    
    if video_id:
        try:
            logger.info(f"Attempting to fetch transcript for {video_id}")
            transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
            
            transcript = None
            try:
                transcript = transcript_list.find_transcript(['ar'])
                logger.info("Found manual Arabic transcript.")
            except Exception:
                try:
                    transcript = transcript_list.find_generated_transcript(['ar'])
                    logger.info("Found auto-generated Arabic transcript.")
                except Exception:
                    logger.info("No Arabic transcript found. Falling back to yt-dlp.")
                    pass
            
            if transcript:
                data = transcript.fetch()
                text = " ".join([item['text'] for item in data])
                return text.strip(), "transcript"
                
        except Exception as e:
            logger.warning(f"youtube-transcript-api failed for video {video_id}: {e}")

    # Step 2: Fallback to yt-dlp
    logger.info("Falling back to yt-dlp + whisper audio extraction.")
    return _extract_audio_and_transcribe(youtube_url), "yt_dlp"

def _extract_video_id(url):
    import re
    # Covers https://www.youtube.com/watch?v=... and https://youtu.be/...
    match = re.search(r'(?:v=|\/)([0-9A-Za-z_-]{11}).*', url)
    return match.group(1) if match else None

def get_youtube_video_duration_fast(youtube_url):
    """
    Attempts to get video duration from youtube-transcript-api metadata.
    Returns duration in seconds if successful, else None.
    Only checks for 'ar' transcripts to align with the Arabic-only rule.
    """
    video_id = _extract_video_id(youtube_url)
    if not video_id:
        return None
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
        transcript = None
        try:
            transcript = transcript_list.find_transcript(['ar'])
        except Exception:
            try:
                transcript = transcript_list.find_generated_transcript(['ar'])
            except Exception:
                pass
        
        if transcript:
            data = transcript.fetch()
            if data:
                last_segment = data[-1]
                duration_sec = last_segment.get('start', 0) + last_segment.get('duration', 0)
                return int(duration_sec)
    except Exception as e:
        logger.warning(f"Fast duration check failed for {video_id}: {e}")
    return None

def _extract_audio_and_transcribe(youtube_url):
    audio_path = None
    wav_path = None
    try:
        audio_path = download_youtube_audio(youtube_url)
        wav_path = audio_path.replace(".mp3", ".wav")
        
        subprocess.run(
            ["ffmpeg", "-i", audio_path, "-ar", "16000", "-ac", "1", "-y", wav_path],
            capture_output=True,
            timeout=30,
            check=True
        )

        with open(wav_path, "rb") as f:
            wav_data = f.read()

        stt_client = SpeechToTextClient()
        files = {"file": ("audio.wav", wav_data, "audio/wav")}
        data = {"language": "ar", "task": "transcribe"}

        response = httpx.post(
            stt_client.base_url + "/",
            files=files,
            data=data,
            timeout=60,
        )
        response.raise_for_status()
        return response.json().get("text", "")
        
    finally:
        if audio_path and os.path.exists(audio_path):
            os.remove(audio_path)
        if wav_path and os.path.exists(wav_path):
            os.remove(wav_path)
