# Generated by Django 5.2.6 on 2026-01-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('cv', 'Computer Vision'), ('nlp', 'NLP'), ('speech', 'Speech')], max_length=20)),
                ('endpoint', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=20)),
                ('latency_ms', models.PositiveIntegerField(help_text='Latency in milliseconds')),
                ('credits_used', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
