# Generated by Django 5.2.6 on 2026-01-09 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['user'], name='ai_aireques_user_id_ba9eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['service'], name='ai_aireques_service_edcad5_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['created_at'], name='ai_aireques_created_438c59_idx'),
        ),
    ]
