# Generated by Django 5.2.6 on 2026-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airequest',
            name='credits_used',
        ),
        migrations.AddField(
            model_name='airequest',
            name='tokens_used',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
