# Generated by Django 5.2.6 on 2026-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_airequest_table_conversation_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiModelTranslationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.TextField()),
                ('winner_model', models.CharField(max_length=50)),
                ('winner_latency_ms', models.PositiveIntegerField()),
                ('mbart_output', models.TextField(blank=True, null=True)),
                ('mbart_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('mt5_output', models.TextField(blank=True, null=True)),
                ('mt5_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('nllb_output', models.TextField(blank=True, null=True)),
                ('nllb_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_multimodel_translation_metric',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['winner_model'], name='ai_multimod_winner__766699_idx'), models.Index(fields=['created_at'], name='ai_multimod_created_5cd31a_idx')],
            },
        ),
    ]
