# Generated by Django 5.2.6 on 2026-05-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubetranslation',
            name='source',
            field=models.CharField(blank=True, choices=[('transcript', 'Transcript'), ('yt_dlp', 'yt-dlp'), ('upload', 'Upload')], max_length=20, null=True),
        ),
    ]
