# Generated by Django 5.2.6 on 2026-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_v1', '0003_alter_youtubetranslation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubetranslation',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='youtubetranslation',
            name='segments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='youtubetranslation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='youtubetranslation',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='youtubetranslation',
            name='source',
            field=models.CharField(blank=True, choices=[('transcript', 'Transcript'), ('transcript_panel', 'Transcript Panel'), ('live_captions', 'Live Captions'), ('yt_dlp', 'yt-dlp'), ('upload_fallback', 'Upload Fallback'), ('upload', 'Upload')], max_length=20, null=True),
        ),
    ]
